import { getServiceClient } from "./requestAuthService.js";
import { completeDemoPayment } from "./paymentRequestService.js";
import bcrypt from "bcryptjs";
import crypto from "crypto";
import { createVerifiedMemberAccount } from "./authRegistrationService.js";

const BCRYPT_ROUNDS = 10;
const DEFAULT_MEMBER_PASSWORD = "Member@123";

function normalizeEmail(email) {
  return String(email || "").trim().toLowerCase();
}

function normalizeUsername(username) {
  return String(username || "").trim();
}

function splitFullName(fullName) {
  const parts = String(fullName || "").trim().split(/\s+/).filter(Boolean);
  if (!parts.length) return { firstName: "", lastName: "" };
  if (parts.length === 1) return { firstName: parts[0], lastName: "" };
  return { firstName: parts[0], lastName: parts.slice(1).join(" ") };
}

function slugify(value) {
  return String(value || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function buildStaffMemberUsername(payload = {}) {
  if (payload.username) return normalizeUsername(payload.username);
  const base = (slugify(payload.fullName) || "member").slice(0, 23).replace(/[-._]+$/g, "") || "member";
  const suffix = String(payload.phoneNumber || crypto.randomInt(1000, 9999)).slice(-6);
  return `${base}-${suffix}`;
}

export function prepareStaffMemberCredentials(payload = {}) {
  return {
    email: normalizeEmail(payload.email),
    password: String(payload.password || "").trim() || DEFAULT_MEMBER_PASSWORD,
  };
}

export function validateStaffMemberCredentials(payload = {}) {
  const email = normalizeEmail(payload.email);
  if (!email) return "Email is required.";
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return "Please enter a valid email address.";
  if (String(payload.password || "").trim() && String(payload.password).length < 8) {
    return "Password must be at least 8 characters.";
  }
  return "";
}

export async function createMemberByStaff(payload, authenticatedClient = null) {
  const client = authenticatedClient || getServiceClient();
  if (!client) {
    return {
      ok: false,
      message: "Backend Supabase service role is not configured.",
    };
  }

  try {
    const credentialError = validateStaffMemberCredentials(payload);
    if (credentialError) {
      return { ok: false, status: 400, message: credentialError };
    }

    const credentials = prepareStaffMemberCredentials(payload);
    const rawPassword = credentials.password;
    const passwordHash = await bcrypt.hash(rawPassword, BCRYPT_ROUNDS);
    const { firstName, lastName } = splitFullName(payload.fullName);
    const email = credentials.email;
    const username = buildStaffMemberUsername(payload);

    const createdAccount = await createVerifiedMemberAccount(client, {
      firstName,
      lastName,
      username,
      email,
      password: rawPassword,
      passwordHash,
      phone: String(payload.phoneNumber || "").trim(),
      dob: payload.dateOfBirth,
      gender: payload.gender || "unspecified",
      occupation: payload.occupation || "",
      address: payload.address || "",
      citizenId: payload.idCard || payload.citizenId || "",
      memberCode: payload.memberCode || "",
    }, {
      accountStatus: "active",
      memberStatus: "active",
      joinDate: new Date().toISOString().slice(0, 10),
    });

    const memberId = createdAccount.memberId;
    const userId = createdAccount.userId;
    const memberCode = createdAccount.memberCode;

    if (payload.packageId) {
      const checkoutPayload = {
        userId: userId,
        memberId: memberId,
        packageId: payload.packageId,
        trainerId: payload.trainerId || null,
        selectedSlots: payload.weeklySlots || [],
        paymentMethod: payload.paymentMethod || "cash",
        purchasedSessions: payload.purchasedSessions || undefined,
        checkoutKey: crypto.randomUUID()
      };

      const checkoutResult = await completeDemoPayment(checkoutPayload);
      if (!checkoutResult.ok) {
        await client.from("users").delete().eq("user_id", userId);
        return {
          ok: false,
          message: "Failed to process package payment: " + checkoutResult.message
        };
      }
    }

    return {
      ok: true,
      data: {
        memberId,
        userId,
        memberCode,
        credentials: {
          email,
          username,
          password: rawPassword,
          autoGenerated: !payload.username || !String(payload.password || "").trim(),
        },
      },
      message: "Member registered successfully."
    };

  } catch (error) {
    console.error("[Staff] Failed to create member:", error);
    const detail = String(error?.message || "");
    if (/already exists/i.test(detail)) {
      return { ok: false, status: 409, message: detail };
    }
    return { ok: false, status: 500, message: "Could not create member. " + detail };
  }
}
